
#Set language manually(en,zh_cn,zh_tw)
#lang: en
lang:

#Tax rate
TaxRate: 0.005

#The tax beneficiary
OP:

#The average balance of single player in mathematical expectation
BasicProperty: 500000

#Enable and make the numbers approximate(shorter and easier to read)
Round: false

# For SlimeFun Plugin
# Enable this option to block any items with lore being sold
# Attention, this might cause the NBT support disable
Filter: false



